# [dbo].[costCenterDesignation]

In [0]:
USE [PLEDIGITAL2]
GO

In [0]:
/****** Object:  Table [dbo].[costCenterDesignation]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[costCenterDesignation](
	[costCenterID] [int] NOT NULL,
	[costCenter] [varchar](200) NULL,
	[denomination] [varchar](200) NULL,
	[responsible] [varchar](200) NULL,
	[vp] [varchar](200) NULL
) ON [PRIMARY]
GO

# [dbo].[costCenterGridTemplate]

In [0]:
/****** Object:  Table [dbo].[costCenterGridTemplate]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[costCenterGridTemplate](
	[costCenterSubID] [int] NOT NULL,
	[costCenterParentID] [int] NULL,
	[contaGerencial] [varchar](200) NULL,
	[january] [decimal](18, 2) NULL,
	[february] [decimal](18, 2) NULL,
	[march] [decimal](18, 2) NULL,
	[april] [decimal](18, 2) NULL,
	[may] [decimal](18, 2) NULL,
	[june] [decimal](18, 2) NULL,
	[july] [decimal](18, 2) NULL,
	[august] [decimal](18, 2) NULL,
	[september] [decimal](18, 2) NULL,
	[october] [decimal](18, 2) NULL,
	[november] [decimal](18, 2) NULL,
	[december] [decimal](18, 2) NULL,
	[totalValue] [decimal](18, 2) NULL
) ON [PRIMARY]
GO

# [dbo].[costCenterParent]

In [0]:
/****** Object:  Table [dbo].[costCenterParent]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[costCenterParent](
	[costCenterID] [int] NOT NULL,
	[versionID] [varchar](200) NULL,
	[managerID] [varchar](200) NULL,
	[status] [varchar](200) NULL,
	[costCenterCode] [varchar](200) NULL,
	[costCenterName] [varchar](200) NULL,
	[user] [varchar](200) NULL,
	[vp] [varchar](200) NULL,
	[allocatedValue] [decimal](18, 2) NULL,
	[usedValue] [decimal](18, 2) NULL
) ON [PRIMARY]
GO

# [dbo].[costCenterSub]

In [0]:
/****** Object:  Table [dbo].[costCenterSub]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[costCenterSub](
	[costCenterSubID] [int] NOT NULL,
	[costCenterParentID] [int] NULL,
	[managerID] [int] NULL,
	[versionID] [int] NULL,
	[contaGerencial] [varchar](200) NULL,
	[january] [decimal](18, 2) NULL,
	[february] [decimal](18, 2) NULL,
	[march] [decimal](18, 2) NULL,
	[april] [decimal](18, 2) NULL,
	[may] [decimal](18, 2) NULL,
	[june] [decimal](18, 2) NULL,
	[july] [decimal](18, 2) NULL,
	[august] [decimal](18, 2) NULL,
	[september] [decimal](18, 2) NULL,
	[october] [decimal](18, 2) NULL,
	[november] [decimal](18, 2) NULL,
	[december] [decimal](18, 2) NULL
) ON [PRIMARY]
GO

# [dbo].[CSKU]

In [0]:
/****** Object:  Table [dbo].[CSKU]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CSKU](
	[KSTAR] [nvarchar](255) NULL,
	[LTEXT] [nvarchar](255) NULL
) ON [PRIMARY]
GO

# [dbo].[managerParent]

In [0]:
/****** Object:  Table [dbo].[managerParent]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[managerParent](
	[managerID] [int] NOT NULL,
	[versionID] [varchar](50) NULL,
	[managerName] [varchar](200) NULL,
	[allocatedInvestment] [decimal](18, 2) NULL,
	[usedInvestment] [decimal](18, 2) NULL,
	[status] [varchar](50) NULL
) ON [PRIMARY]
GO

# [dbo].[sapExportCostCenter]

In [0]:
/****** Object:  Table [dbo].[sapExportCostCenter]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sapExportCostCenter](
	[KOSTL] [varchar](11) NULL,
	[LTEXT] [varchar](255) NULL
) ON [PRIMARY]
GO

# [dbo].[sapExportHistoric]

In [0]:
/****** Object:  Table [dbo].[sapExportHistoric]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sapExportHistoric](
	[OBJNR] [varchar](50) NOT NULL,
	[KSTAR] [varchar](15) NOT NULL,
	[GJAHR] [int] NOT NULL,
	[WTG001] [float] NULL,
	[WTG002] [float] NULL,
	[WTG003] [float] NULL,
	[WTG004] [float] NULL,
	[WTG005] [float] NULL,
	[WTG006] [float] NULL,
	[WTG007] [float] NULL,
	[WTG008] [float] NULL,
	[WTG009] [float] NULL,
	[WTG010] [float] NULL,
	[WTG011] [float] NULL,
	[WTG012] [float] NULL
) ON [PRIMARY]
GO

# [dbo].[users]

In [0]:
/****** Object:  Table [dbo].[users]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[userID] [int] NOT NULL,
	[name] [varchar](50) NULL,
	[login] [varchar](8) NULL,
	[permission] [varchar](100) NULL,
	[email] [varchar](100) NULL,
	[themePreference] [int] NULL
) ON [PRIMARY]
GO

# [dbo].[versionParent]

In [0]:
/****** Object:  Table [dbo].[versionParent]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[versionParent](
	[versionID] [int] NOT NULL,
	[status] [varchar](200) NULL,
	[step] [varchar](200) NULL,
	[plannedInvestment] [decimal](18, 2) NULL,
	[usedInvestment] [decimal](18, 2) NULL,
	[creationDate] [datetime] NULL,
	[finishDate] [datetime] NULL
) ON [PRIMARY]
GO

# [dbo].[vpList]

In [0]:
/****** Object:  Table [dbo].[vpList]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[vpList](
	[vpListId] [int] NOT NULL,
	[vpName] [varchar](100) NULL,
	[responsable] [varchar](100) NULL
) ON [PRIMARY]
GO

# [dbo].[vpParent]

In [0]:
/****** Object:  Table [dbo].[vpParent]    Script Date: 10/08/2025 22:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[vpParent](
	[vpID] [int] NOT NULL,
	[status] [varchar](500) NULL,
	[versionID] [varchar](100) NULL,
	[vpName] [varchar](50) NULL,
	[vpUser] [varchar](200) NULL,
	[totalInvestment] [decimal](18, 2) NULL
) ON [PRIMARY]
GO